#! /bin/bash

mkdir -p .eclipse-che
cd .eclipse-che

DOCKER_USER=`whoami`

echo "[ -d eclipse-che-latest ] || sudo bash ../.provision-che.sh $DOCKER_USER"
[ -d eclipse-che-latest ] || sudo bash ../.provision-che.sh $DOCKER_USER

sudo service docker start
sudo usermod -aG docker $DOCKER_USER

CHE_IP="127.0.0.1"
[ "$1" != "" ] && CHE_IP="$1"

CHE_IP=`( ip addr list $CHE_IP 2> /dev/null || ip addr list | grep $CHE_IP 2> /dev/null ) | grep "inet " | cut -d' ' -f6 | cut -d/ -f1`

bash ../.provision-che-boot.sh $CHE_IP
