# mainly => https://gist.github.com/serainville/b55635a5f808e7d12397fd81ca860d44
# wttf =>  https://cloud.netapp.com/blog/how-to-set-up-mysql-kubernetes-deployments
# wtf => https://www.serverlab.ca/tutorials/containers/kubernetes/how-to-run-wordpress-and-mysql-5-7-on-kubernetes/
# kubecon => https://www.youtube.com/watch?v=J7h0F34iBx0

---
apiVersion: v1
kind: Secret
metadata:
  name: hello-wp-mysql-secrets
type: Opaque
data:
  ROOT_PASSWORD: d2VsdGVzdAo=
  USER_PASSWORD: d2VsdGVzdAo=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-wp-mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "mysql"
              name: mysqldb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: weltest
              # valueFrom:
              #   secretKeyRef:
              #     name: hello-wp-mysql-secrets
              #     key: ROOT_PASSWORD
            - name: MYSQL_USER
              value: hello-wp-user
            - name: MYSQL_PASSWORD
              value: weltest
              # valueFrom:
              #   secretKeyRef:
              #     name: hello-wp-mysql-secrets
              #     key: USER_PASSWORD
            - name: MYSQL_DATABASE
              value: hello-wp-db
      volumes:
        - name: mysqldb
          hostPath:
            path: /tmp/hello-wp-volume
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: hello-wp-mysql-service
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306