---
apiVersion: v1
kind: Secret
metadata:
  name: hello-wp-mysql-secrets
type: Opaque
data:
  ROOT_PASSWORD: c3VwZXItc2VjcmV0LXBhc3N3b3JkCg==
  SITE1_USER_PASSWORD: cGFzc3dvcmQxMjMK
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-wp-mysql-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-wp-mysql-deployment
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          # volumeMounts:
          #   - mountPath: "/var/lib/mysql"
          #     subPath: "mysql"
          #     name: mysqldb
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-wp-mysql-secrets
                  key: ROOT_PASSWORD
            - name: MYSQL_USER
              value: site1_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hello-wp-mysql-secrets
                  key: SITE1_USER_PASSWORD
            - name: MYSQL_DATABASE
              value: site1
      # volumes:
      #   - name: mysqldb
      #     persistentVolumeClaim:
      #       claimName: hello-wp-mysql-disk
---
apiVersion: v1
kind: Service
metadata:
  name: hello-wp-mysql-service
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306




# apiVersion: v1
# kind: Secret
# metadata:
#   name: hello-wp-mysql-mysql-secrets
# type: Opaque
# data:
#   ROOT_PASSWORD: c3VwZXItc2VjcmV0LXBhc3N3b3JkCg==
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: hello-wp-mysql-mysql-volume
# spec:
#   accessModes:
#     - ReadWriteMany
#   volumeMode: Filesystem
#   resources:
#     requests:
#       storage: 1Gi
#   storageClassName: high-performance
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: hello-wp-mysql-mysql
#   labels:
#     app: mysql
# spec:
#   selector:
#     matchLabels:
#       app: mysql
#       tier: database
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: mysql
#         tier: database
#     spec:
#       containers:
#       - image: mysql:5
#         name: mysql
#         env:
#         - name: MYSQL_ROOT_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: hello-wp-mysql-mysql-secrets
#               key: password
#         ports:
#           - containerPort: 3306
#             name: mysql
#         volumeMounts:
#           - name: hello-wp-mysql-mysql-volume
#             mountPath: /var/lib/mysql
#       volumes:
#       - name: hello-wp-mysql-mysql-volume
#         persistentVolumeClaim:
#           claimName: hello-wp-mysql-mysql-volume



# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql
# spec:
#   ports:
#   - port: 3306
#   selector:
#     app: mysql
#   clusterIP: None
# ---
# apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
# kind: Deployment
# metadata:
#   name: mysql
# spec:
#   selector:
#     matchLabels:
#       app: mysql
#   strategy:
#     type: Recreate
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#       - image: mysql:5
#         name: mysql
#         env:
#           # Use secret in real usage
#         - name: MYSQL_ROOT_PASSWORD
#           value: password
#         ports:
#         - containerPort: 3306
#           name: mysql
#         volumeMounts:
#         - name: mysql-persistent-storage
#           mountPath: /var/lib/mysql
#       volumes:
#       - name: mysql-persistent-storage
#         persistentVolumeClaim:
#           claimName: mysql-pv-claim

# # apiVersion: v1
# # kind: Service
# # metadata:
# #   name: hello-wp-mysql-mysql
# #   labels:
# #     app: wordpress
# # spec:
# #   ports:
# #     - port: 3306
# #   selector:
# #     app: wordpress
# #     tier: mysql
# # ---
# # apiVersion: v1
# # kind: PersistentVolumeClaim
# # metadata:
# #   name: mysql-pv-claim
# #   labels:
# #     app: wordpress
# # spec:
# #   accessModes:
# #     - ReadWriteOnce
# #   resources:
# #     requests:
# #       storage: 1Gi
# # ---
# apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
# kind: Deployment
# metadata:
#   name: hello-wp-mysql-mysql
#   labels:
#     app: wordpress
# spec:
#   selector:
#     matchLabels:
#       app: wordpress
#       tier: mysql
#   # strategy:
#   #   type: Recreate
#   template:
#     metadata:
#       labels:
#         app: wordpress
#         tier: mysql
#     spec:
#       containers:
#       - image: mysql:5
#         name: mysql
#         env:
#         - name: MYSQL_ROOT_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mysql-pass
#               key: password
#         ports:
#         - containerPort: 3306
#           name: mysql
#         # volumeMounts:
#         # - name: mysql-persistent-storage
#         #   mountPath: /var/lib/mysql
#       # volumes:
#       # - name: mysql-persistent-storage
#       #   persistentVolumeClaim:
#       #     claimName: mysql-pv-claim
