---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxthroughpass
data:
  default.conf: |
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      
      # Set nginx to serve files from the shared volume!
      root /var/www/html;
      server_name _;
      location / {
        try_files $uri $uri/ /index.php?$args =404;
      }
      location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param REQUEST_METHOD $request_method;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass 127.0.0.1:9000;
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: varwwwsafsd
data:
  index.php: |
    <?php phpinfo();
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpapp
  labels:
    app: production
    type: app
    service: phpservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: production
      type: app
      service: phpservice
  template:
    metadata:
      labels:
        app: production
        type: app
        service: phpservice
    spec:
      containers:
        - image: php:7-fpm
          imagePullPolicy: IfNotPresent
          name: app
          volumeMounts:
            - mountPath: /var/www/html
              name: varwww
              readOnly: true
        - image: nginx
          imagePullPolicy: Always
          name: nginx
          volumeMounts:
            - mountPath: /etc/nginx/conf.d
              name: nginxconf
              readOnly: true
            - mountPath: /var/www/html
              name: varwww
              readOnly: true
      volumes:
        - configMap:
            defaultMode: 256
            name: nginxthroughpass
            optional: false
          name: nginxconf
        - configMap:
            defaultMode: 256
            name: varwwwsafsd
            optional: false
          name: varwww