#! /bin/bash

#
#
# @param $1 - "subdomain1.domain1.foo,subdomain2.domain1.foo,subdomain1.domain2.foo|domain1.foo"
#
Certificates::create() {}

#
#
#
Certificates::isValid() {}

#
#
#
Certificates::pathByDomain {}