#! /bin/sh

buildDeps="\
        .build-deps \
        libjpeg-turbo-dev \
        libpng-dev \
        libmcrypt-dev \
        pcre-dev \
"

doNotUninstall="\
    curl \
    mysql-client \
    unzip \
"

apk add --no-cache --virtual $buildDeps $doNotUninstall

includePath="/usr/include/"
docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd
docker-php-ext-configure mysql --with-mysql=mysqlnd
docker-php-ext-configure mysqli --with-mysqli=mysqlnd
docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr
docker-php-ext-install gd
php --version | grep 5.6 && docker-php-ext-install mysql
docker-php-ext-install mysqli pdo_mysql mcrypt zip

apk del $doNotUninstall
rm -rf /var/cache/apk/*

exec php-fpm "$@"