#! /bin/sh

buildDeps="\
        .build-deps \
        libjpeg-turbo-dev \
        libpng-dev \
        libmcrypt \
        pcre-dev \
"

doNotUninstall="\
    curl \
    mysql-client \
    unzip \
"

apk add --no-cache --virtual $buildDeps $doNotUninstall
rm -rf /var/cache/apk/*
includePath="/usr/include/"

docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr
docker-php-ext-install gd mysqli mcrypt zip

apk del $doNotUninstall

exec php-fpm "$@"